import footballImage from 'assets/action-american-football-athletes-field-260697.jpg';
import cedricImage from 'assets/cedric.jpeg';
import audeImage from 'assets/aude.jpeg';
import nadiaImage from 'assets/nadia.jpg';
import * as variables from 'styles/_scss-variables.scss';

const title = 'Lorem ipsum dolor sit amet';
const description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum gravida ipsum ac augue pharetra, sed vehicula libero ornare. Cras et tristique dolor. Etiam scelerisque leo eu turpis accumsan placerat. Morbi aliquet felis vitae lectus dapibus iaculis. Quisque at placerat nisl. Morbi tincidunt elementum lacus vel interdum. Proin congue vulputate semper. Suspendisse potenti. Fusce ullamcorper ipsum quis ornare pulvinar. Nunc id sem tempor, posuere leo ut, maximus massa. Nullam interdum nunc at ex tempus ornare. Morbi ullamcorper, erat eget imperdiet vehicula, sapien felis scelerisque nulla, at congue mauris nibh a est. Pellentesque id fermentum urna, at feugiat dui. Nunc ut dolor sodales, sollicitudin ligula et, rutrum dolor. Quisque semper nisi enim. Sed semper pretium mauris tincidunt fermentum.';
const testimonials = {
  first_user: {
    user_identity: 'Cédric',
    user_testimonial: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum gravida ipsum ac augue pharetra, sed vehicula libero ornare. Cras et tristique dolor. Etiam scelerisque leo eu turpis accumsan placerat.',
    user_picture: cedricImage,
  },
  second_user: {
    user_identity: 'Aude',
    user_testimonial: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum gravida ipsum ac augue pharetra, sed vehicula libero ornare. Cras et tristique dolor. Etiam scelerisque leo eu turpis accumsan placerat.',
    user_picture: audeImage,
  },
  third_user: {
    user_identity: 'Nadia',
    user_testimonial: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum gravida ipsum ac augue pharetra, sed vehicula libero ornare. Cras et tristique dolor. Etiam scelerisque leo eu turpis accumsan placerat.',
    user_picture: nadiaImage,
  },
};

const clubReducer = {
  id: 2,
  name: 'Bayern Munich',
  logo_url: 'https://content.sportslogos.net/logos/7/173/full/299.png',
  zip_code: '38226-0885',
  address: '607 Jones Trafficway',
  country: 'US',
  description: 'Labore cum voluptatem. Enim quia ducimus. Id repellat quo. Vel odit repellendus. Temporibus voluptatibus aut. Corrupti aut explicabo. Sint id temporibus. Dignissimos officiis vel. Iste repellendus aliquam. Deserunt autem molestias. Amet voluptas maxime. Sed impedit consequatur. Quibusdam quis enim. Sunt est beatae. Autem odit nostrum. Rem autem et. Aut qui dolor. Quis dicta id. Corrupti non aspernatur. Quo sed eum. Esse fugit consequuntur. Eos qui eligendi. Recusandae nostrum et. Dicta aperiam numquam. Ut consequatur rerum. Inventore numquam optio. Consequatur ducimus officia. Mollitia porro .',
  city: 'Abdulborough',
  date_of_creation: '2020-07-02',
  league: 'Silver IV',
  conference: 'conference Sud',
  pool: 'pool',
  currentTeam: undefined,
  currentTeams: [
    {
      id: 4,
      title: 'Washington crows',
      coach_id: 2,
      creator_id: 2,
      club_id: 2,
      players: [
        {
          id: 33,
          email: 'kenton@grant.biz',
          first_name: 'Harold',
          last_name: 'Kub',
          phone: '(572) 428-8899',
          birthdate: '1955-09-09',
          arrival: '2020-06-18',
          'availability?': true,
          height: 179,
          weight: 86,
          gender: 'f',
          jersey_number: 29,
          position: '10',
          team_id: 4,
          created_at: '2020-07-13T10:19:05.044Z',
          updated_at: '2020-07-13T10:19:05.044Z',
        },
        {
          id: 36,
          email: 'kasey.feil@dietrich.org',
          first_name: 'Solomon',
          last_name: 'Paucek',
          phone: '(286) 990-2990',
          birthdate: '1971-10-21',
          arrival: '2020-06-15',
          'availability?': true,
          height: 194,
          weight: 72,
          gender: 'f',
          jersey_number: 9,
          position: '5',
          team_id: 4,
          created_at: '2020-07-13T10:19:06.079Z',
          updated_at: '2020-07-13T10:19:06.079Z',
        },
        {
          id: 37,
          email: 'gale@kemmer.net',
          first_name: 'Cameron',
          last_name: 'Armstrong',
          phone: '(321) 476-8351',
          birthdate: '1969-07-27',
          arrival: '2020-07-01',
          'availability?': true,
          height: 199,
          weight: 77,
          gender: 'm',
          jersey_number: 32,
          position: '2',
          team_id: 4,
          created_at: '2020-07-13T10:19:06.397Z',
          updated_at: '2020-07-13T10:19:06.397Z',
        },
      ],
      attendances: {
        games: [
          {
            id: 10,
            title: 'Barclays Premier League',
            long_description: 'Et beatae dolorum. Sunt magni reprehenderit. Sit similique natus. Numquam qui eaque. Perspiciatis quas doloribus. Esse error aliquam. Minus molestias ex. Omnis totam vel. Deserunt ad magni. Rerum sit aut. Adipisci nam eum. Repellat unde sunt. Quasi quis magnam. Magni iure ab. Molestias at culpa. Sit dolorem sequi. Voluptatum omnis ex. Dolorem sunt dolore. Est sint consequatur. Dolores voluptatem .',
            address: '523 Yasmine Points',
            city: 'West Darron',
            country: 'France',
            zip_code: '88446-8168',
            starting_date_time: '2020-09-22T18:07:53.000Z',
            duration: 60,
            home_team_score: 33,
            away_team_score: 49,
            canceled: true,
            created_at: '2020-07-13T10:18:53.344Z',
            updated_at: '2020-07-13T10:18:53.344Z',
          },
          {
            id: 7,
            title: 'Nations Cup',
            long_description: 'Omnis animi non. Odit expedita sapiente. Voluptates et aut. Enim illum tempora. Dolorem sunt aspernatur. Voluptatem voluptas est. Eius et est. Laboriosam autem totam. Eaque qui ea. Eum et quis. Voluptatibus quo non. Quia molestiae sed. Quia similique aut. Sint consequatur consectetur. Culpa ex quos. Qui quis voluptatem. Quos fugit quas. Quasi repellendus veniam. Sint voluptates nihil. Sunt repreh.',
            address: '766 Easter Hill',
            city: 'North Argentina',
            country: 'France',
            zip_code: '33018-5125',
            starting_date_time: '2020-09-21T19:12:18.000Z',
            duration: 30,
            home_team_score: 57,
            away_team_score: 10,
            canceled: true,
            created_at: '2020-07-13T10:18:53.311Z',
            updated_at: '2020-07-13T10:18:53.311Z',
          },
          {
            id: 2,
            title: 'Copa America',
            long_description: 'Molestias quis minus. Provident debitis necessitatibus. Qui praesentium est. Et id eius. Expedita est quas. Aspernatur ipsa sapiente. Cupiditate dolorum et. Dignissimos optio expedita. Aspernatur provident sint. Perferendis aliquid in. Quo aperiam quaerat. Et autem et. Qui vero sapiente. Quas dolorem laborum. Magni id esse. Veritatis totam cupiditate. Quia accusantium laborum. Occaecati voluptas .',
            address: '682 Pearline Trafficway',
            city: 'West Wmville',
            country: 'France',
            zip_code: '18788-7918',
            starting_date_time: '2020-09-22T15:15:33.000Z',
            duration: 45,
            home_team_score: 38,
            away_team_score: 87,
            canceled: true,
            created_at: '2020-07-13T10:18:53.256Z',
            updated_at: '2020-07-13T10:18:53.256Z',
          },
        ],
        practices: [
          {
            id: 12,
            title: 'training session',
            long_description: 'Quae repellendus delectus. Ipsam optio ad. Qui assumenda iusto. Ut repellat magnam. Est iusto dignissimos. Maiores aut velit. Sunt quidem qui. Ratione et sit. Excepturi alias delectus. Magni ratione voluptas. Et quasi aut. Ut dolorum accusamus. Nesciunt perspiciatis rem. Quia illum amet. Ut nesciunt quisquam. Voluptatem et voluptatem. Iste sed expedita. Odio recusandae deserunt. Excepturi reicien.',
            address: '30594 Jimmy Isle',
            city: 'Wildermanmouth',
            country: 'US',
            zip_code: '08943-1506',
            starting_date_time: '2020-09-20T18:09:25.000Z',
            duration: 90,
            canceled: false,
            created_at: '2020-07-13T10:19:28.450Z',
            updated_at: '2020-07-13T10:19:28.450Z',
          },
        ],
      },
    },
    {
      id: 5,
      title: 'North Dakota conspirators',
      coach_id: 2,
      creator_id: 2,
      club_id: 2,
      players: [
        {
          id: 18,
          email: 'logan@fay.name',
          first_name: 'Amos',
          last_name: 'Parker',
          phone: '188.341.3422',
          birthdate: '2004-07-28',
          arrival: '2020-06-17',
          'availability?': true,
          height: 192,
          weight: 78,
          gender: 'f',
          jersey_number: 35,
          position: '10',
          team_id: 5,
          created_at: '2020-07-13T10:19:00.036Z',
          updated_at: '2020-07-13T10:19:00.036Z',
        },
        {
          id: 45,
          email: 'stefanie_morar@aufderhar.com',
          first_name: 'Lamar',
          last_name: 'Paucek',
          phone: '(289) 306-7424',
          birthdate: '1977-04-05',
          arrival: '2020-05-21',
          'availability?': true,
          height: 187,
          weight: 87,
          gender: 'm',
          jersey_number: 61,
          position: '8',
          team_id: 5,
          created_at: '2020-07-13T10:19:09.109Z',
          updated_at: '2020-07-13T10:19:09.109Z',
        },
        {
          id: 52,
          email: 'marcos_emmerich@keebler.biz',
          first_name: 'Neville',
          last_name: 'Hauck',
          phone: '632-980-1055',
          birthdate: '2002-01-10',
          arrival: '2020-06-05',
          'availability?': true,
          height: 191,
          weight: 90,
          gender: 'f',
          jersey_number: 79,
          position: '9',
          team_id: 5,
          created_at: '2020-07-13T10:19:11.392Z',
          updated_at: '2020-07-13T10:19:11.392Z',
        },
      ],
      attendances: {
        games: [
          {
            id: 11,
            title: 'UEFA Europa League',
            long_description: 'Est pariatur veniam. Suscipit quaerat dolores. Optio odio architecto. Vero voluptatem quia. Quidem modi consectetur. Qui et laudantium. Velit aspernatur in. Ad est aperiam. Et aut et. Quod ad numquam. Quaerat reiciendis magni. Dolorum est quia. Eligendi quibusdam voluptatem. Est praesentium facilis. Facilis voluptatum animi. Optio iste porro. Reiciendis eos voluptas. Magni et voluptatem. Qui iure.',
            address: '3466 Quintin Fall',
            city: 'East Nigel',
            country: 'France',
            zip_code: '28360',
            starting_date_time: '2020-09-22T18:57:34.000Z',
            duration: 60,
            home_team_score: 15,
            away_team_score: 70,
            canceled: true,
            created_at: '2020-07-13T10:18:53.355Z',
            updated_at: '2020-07-13T10:18:53.355Z',
          },
        ],
        practices: [
          {
            id: 3,
            title: 'training session',
            long_description: 'Omnis dignissimos cum. Enim voluptatem minima. Adipisci repudiandae praesentium. Commodi dignissimos ut. Aperiam rerum nemo. Maxime explicabo quia. Aut accusamus enim. In adipisci dolor. Sit aut dolorem. At neque rerum. Officiis vel necessitatibus. Facere nesciunt occaecati. Natus iste culpa. Dignissimos qui sed. Omnis est blanditiis. Dolore dolor quo. Earum quos tempore. Non voluptatem animi. Es.',
            address: '67899 Abshire Summit',
            city: 'Janellafort',
            country: 'US',
            zip_code: '23187-6002',
            starting_date_time: '2020-09-19T17:18:55.000Z',
            duration: 15,
            canceled: true,
            created_at: '2020-07-13T10:19:28.340Z',
            updated_at: '2020-07-13T10:19:28.340Z',
          },
          {
            id: 10,
            title: 'training session',
            long_description: 'Reprehenderit officia ut. Tempora suscipit laborum. Tempore magnam quasi. Quia delectus eum. Occaecati alias sit. Vel animi et. Impedit ut voluptatum. Deleniti vel consequatur. Quo et libero. Tempora aut laborum. Ut consequuntur quod. Sit necessitatibus quo. Sequi quasi deserunt. Molestiae voluptatem ut. Commodi velit qui. Sunt vero aut. Voluptatem voluptatum facilis. Maxime ducimus qui. Libero e.',
            address: '1035 Schinner Green',
            city: 'Evehaven',
            country: 'US',
            zip_code: '23322-7917',
            starting_date_time: '2020-09-20T17:56:33.000Z',
            duration: 30,
            canceled: true,
            created_at: '2020-07-13T10:19:28.428Z',
            updated_at: '2020-07-13T10:19:28.428Z',
          },
        ],
      },
    },
  ],
};

const themeColors = {
  'Ogres de créteil': variables.purpleColor,
};

export {
  footballImage, cedricImage, audeImage, nadiaImage,
  title, description, testimonials,
  clubReducer,
};
