const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const DISPLAY_SUCCESS_MESSAGE = 'DISPLAY_SUCCESS_MESSAGE';
const RESET_SUCCESS_MESSAGE = 'RESET_SUCCESS_MESSAGE';
const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

export {
  LOGOUT_SUCCESS, LOGIN_FAILURE, LOGIN_REQUEST, LOGIN_SUCCESS,
  RESET_SUCCESS_MESSAGE, DISPLAY_SUCCESS_MESSAGE, RESET_ERROR_MESSAGE,
};
