const UPDATE_CURRENT_CLUB = 'UPDATE_CURRENT_CLUB';
const UPDATE_CURRENT_TEAMS = 'UPDATE_CURRENT_TEAMS';
const ADD_TEAM_TO_CURRENT_TEAMS = 'ADD_TEAM_TO_CURRENT_TEAMS';
const UPDATE_CURRENT_TEAM = 'UPDATE_CURRENT_TEAM';
const UPDATE_CURRENT_ATTENDANCES = 'UPDATE_CURRENT_ATTENDANCES';
const UPDATE_CURRENT_PLAYER = 'UPDATE_CURRENT_PLAYER';

export {
  UPDATE_CURRENT_CLUB, UPDATE_CURRENT_TEAMS, ADD_TEAM_TO_CURRENT_TEAMS, UPDATE_CURRENT_TEAM,
  UPDATE_CURRENT_ATTENDANCES, UPDATE_CURRENT_PLAYER,
};
