const UPDATE_CURRENT_CLUB = 'UPDATE_CURRENT_CLUB';
const UPDATE_CURRENT_TEAMS = 'UPDATE_CURRENT_TEAMS';
const ADD_TEAM_TO_CURRENT_TEAMS = 'ADD_TEAM_TO_CURRENT_TEAMS';

export { UPDATE_CURRENT_CLUB, UPDATE_CURRENT_TEAMS, ADD_TEAM_TO_CURRENT_TEAMS };
